from pathlib import Path

# Qatorlarni list ko'rinishida beramiz, bu newline yo'qolishini oldini oladi
lines = [
    "from django.shortcuts import render, redirect, get_object_or_404",
    "from django.http import JsonResponse",
    "from django.contrib.auth import login, logout, authenticate",
    "from django.contrib.auth.models import User",
    "from django.contrib.auth.decorators import login_required",
    "from .models import Faculty, Kafedra, Group, Student, Subject, Teacher, Category, Product, Order, OrderItem, AuditLog, Branch",
    "from .forms import FacultyForm, KafedraForm, GroupForm, StudentForm, SubjectForm, TeacherForm, CategoryForm, ProductForm, OrderForm, OrderItemForm, BranchForm",
    "from . import services",
    "import json",
    "",
    "def _client_ip(request):",
    "    forwarded = request.META.get('HTTP_X_FORWARDED_FOR')",
    "    if forwarded:",
    "        return forwarded.split(',')[0].strip()",
    "    return request.META.get('REMOTE_ADDR')",
    "",
    "def _log_action(request, *, action, entity, entity_id=None, message=''):",
    "    try:",
    "        AuditLog.objects.create(",
    "            user=request.user if getattr(request, 'user', None) and request.user.is_authenticated else None,",
    "            action=action,",
    "            entity=entity,",
    "            entity_id=entity_id,",
    "            message=message[:255],",
    "            ip_address=_client_ip(request),",
    "            user_agent=(request.META.get('HTTP_USER_AGENT') or '')[:255],",
    "        )",
    "    except: pass",
    "",
    "def login_required_decorator(func):",
    "    return login_required(func, login_url='login_page')",
    "",
    "@login_required_decorator",
    "def logout_page(request):",
    "    logout(request)",
    "    return redirect('login_page')",
    "",
    "def login_page(request):",
    "    error = None",
    "    if request.method == 'POST':",
    "        user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))",
    "        if user:",
    "            login(request, user)",
    "            return redirect('dashboard')",
    "        error = 'Login yoki parol xato'",
    "    return render(request, 'login.html', {'error': error})",
    "",
    "@login_required_decorator",
    "def home_page(request):",
    "    context = {",
    "        'counts': {",
    "            'orders': Order.objects.count(),",
    "            'revenue': sum(o.total_price for o in Order.objects.all()),",
    "            'products': Product.objects.count(),",
    "            'categories': Category.objects.count(),",
    "            'teachers': Teacher.objects.count(),",
    "            'students': Student.objects.count()",
    "        }",
    "    }",
    "    return render(request, 'dashboard.html', context)",
    "",
    "def product_list(request):",
    "    categories = Category.objects.prefetch_related('products').all()",
    "    return render(request, 'index_1.html', {",
    "        'categories': categories,",
    "        'cart_total': request.session.get('cart_total', 0)",
    "    })",
    "",
    "def filiallar_page(request):",
    "    branches = Branch.objects.all()",
    "    return render(request, 'filiallar.html', {",
    "        'branches': branches,",
    "        'cart_total': request.session.get('cart_total', 0)",
    "    })",
    "",
    "@login_required_decorator",
    "def profile(request): return render(request, 'profile.html')",
    "",
    "def add_to_cart(request):",
    "    if request.method == 'POST':",
    "        pid = request.POST.get('product_id')",
    "        product = get_object_or_404(Product, id=pid)",
    "        cart = request.session.get('cart', {})",
    "        if str(pid) in cart: cart[str(pid)]['quantity'] += 1",
    "        else: cart[str(pid)] = {'name': product.name, 'price': float(product.price), 'quantity': 1}",
    "        request.session['cart'] = cart",
    "        request.session['cart_total'] = sum(i['price'] * i['quantity'] for i in cart.values())",
    "        return JsonResponse({'success': True, 'cart_total': request.session['cart_total']})",
    "    return JsonResponse({'success': False})",
    "",
    "def cart_modal(request):",
    "    cart = request.session.get('cart', {})",
    "    items = []",
    "    for pid, item in cart.items():",
    "        try: items.append({'product': Product.objects.get(id=pid), 'quantity': item['quantity'], 'total': item['price'] * item['quantity']})",
    "        except: continue",
    "    return render(request, 'cart_modal.html', {'items': items, 'total': request.session.get('cart_total', 0)})",
    "",
    "def clear_cart(request):",
    "    request.session['cart'] = {}; request.session['cart_total'] = 0",
    "    return JsonResponse({'success': True})",
    "",
    "@login_required_decorator",
    "def product_admin_list(request): return render(request, 'product/list.html', {'models': Product.objects.all()})",
    "@login_required_decorator",
    "def category_list(request): return render(request, 'category/list.html', {'models': Category.objects.all()})",
    "@login_required_decorator",
    "def teacher_list(request): return render(request, 'teacher/list.html', {'teachers': services.get_teacher()})",
    "@login_required_decorator",
    "def student_list(request): return render(request, 'student/list.html', {'students': services.get_student()})",
    "@login_required_decorator",
    "def branch_list(request): return render(request, 'branch/list.html', {'models': Branch.objects.all()})",
    "@login_required_decorator",
    "def order_admin_list(request): return render(request, 'order/list.html', {'models': Order.objects.all().order_by('-created_at')})",
    "",
    "@login_required_decorator",
    "def faculty_list(request): return render(request, 'faculty/list.html', {'faculties': services.get_faculties()})",
    "@login_required_decorator",
    "def kafedra_list(request): return render(request, 'kafedra/list.html', {'kafedras': services.get_kafedra()})",
    "@login_required_decorator",
    "def subject_list(request): return render(request, 'subject/list.html', {'subjects': services.get_subject()})",
    "@login_required_decorator",
    "def group_list(request): return render(request, 'group/list.html', {'groups': services.get_groups()})",
    "",
    "def category_create(request): return redirect('category_list')",
    "def category_edit(request, pk): return redirect('category_list')",
    "def category_delete(request, pk): return redirect('category_list')",
    "def product_create(request): return redirect('product_admin_list')",
    "def product_edit(request, pk): return redirect('product_admin_list')",
    "def product_delete(request, pk): return redirect('product_admin_list')",
    "def faculty_create(request): pass",
    "def faculty_edit(request, pk): pass",
    "def faculty_delete(request, pk): pass",
    "def kafedra_create(request): pass",
    "def kafedra_edit(request, pk): pass",
    "def kafedra_delete(request, pk): pass",
    "def subject_create(request): pass",
    "def subject_edit(request, pk): pass",
    "def subject_delete(request, pk): pass",
    "def teacher_create(request): pass",
    "def teacher_edit(request, pk): pass",
    "def teacher_delete(request, pk): pass",
    "def group_create(request): pass",
    "def group_edit(request, pk): pass",
    "def group_delete(request, pk): pass",
    "def student_create(request): pass",
    "def student_edit(request, pk): pass",
    "def student_delete(request, pk): pass",
    "def admin_user_list(request): return redirect('dashboard')",
    "def admin_user_create(request): pass",
    "def admin_user_password(request, pk): pass",
    "def admin_user_delete(request, pk): pass",
    "def branch_create(request): return redirect('branch_list')",
    "def branch_edit(request, pk): return redirect('branch_list')",
    "def branch_delete(request, pk): return redirect('branch_list')",
    "def order_create(request): return JsonResponse({'success':True})",
    "def order_page(request): return render(request, 'order.html')",
    "def order_delete(request, pk): return redirect('order_admin_list')",
    "def update_cart(request): return JsonResponse({'success':True})"
]

# Faylni xavfsiz qatorlar bo'yicha yozish
Path('adminapp/views.py').write_text('\\n'.join(lines), encoding='utf-8')
print("✅ adminapp/views.py muvaffaqiyatli tiklandi.")
