# Generated by Django 6.0.2 on 2026-03-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_add_phone_address_specialization_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Filial nomi')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Ish vaqti')),
                ('location_url', models.URLField(blank=True, verbose_name='Google Maps linki')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
            },
        ),
    ]
