# Generated by Django 6.0.2 on 2026-03-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_group_faculty_remove_student_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='location_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Google Maps linki'),
        ),
    ]
